name: ci

on:
  push:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Install Flake8
        run: |
          python3 -m pip install flake8
      -
        name: Run Flake8
        run: |
          python3 -m flake8
