name: get-pip-pyopenssl

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          ["2.6", "2.7", "3.2", "3.3", "3.4", "3.5", "3.6", "3.7", "3.8",
           "3.9", "3.10"]
      max-parallel: 6
      fail-fast: false
    container: "pylegacy/python:${{ matrix.python-version }}-debian-5"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Install lint requirements
        run: |
          pip install -r requirements-lint.txt
      -
        name: Run Flake8
        run: |
          if [ -x "$(command -v flake8)" ]; then flake8; fi
      -
        name: Run PyLint
        run: |
          if [ -x "$(command -v pylint)" ]; then pylint scripts/*.py; fi

  build:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          ["3.6"]
      max-parallel: 1
      fail-fast: false
    container: "pylegacy/python:${{ matrix.python-version }}-debian-5"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build
        run: |
          python scripts/build.py --dest dist --remote http://pylegacy.org/hub
      -
        name: Upload build artifacts
        uses: actions/upload-artifact@v1
        with:
          name: artifacts-build
          path: dist

  upload:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.REMOTE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      -
        name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: artifacts-build
          path: dist
      -
        name: Sync static site
        run: |
          rsync -avP dist/                                                    \
              ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_ROOT }}/hub
