name: get-pip-pyopenssl

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          ["2.6", "2.7", "3.2", "3.3", "3.4", "3.5", "3.6", "3.7", "3.8",
           "3.9", "3.10"]
      max-parallel: 6
      fail-fast: false
    container: "pylegacy/python:${{ matrix.python-version }}-debian-5"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Install lint requirements
        run: |
          pip install -r requirements-lint.txt
      -
        name: Run Flake8
        run: |
          if [ -x "$(command -v flake8)" ]; then flake8; fi
      -
        name: Run PyLint
        run: |
          if [ -x "$(command -v pylint)" ]; then pylint scripts/*.py; fi
